root = "."

[tmp]
  path = "./tmp"

[build]
  bin = "tmp/main.exe"
  cmd = "go build -o tmp/main.exe ."

[run]
  executable = "tmp/main.exe"
  args = []

[restart]
  exclude_ext = [".git", ".idea", "tmp", "vendor"]
  include_ext = [".go", ".mod", ".sum"]
